object MyVersions {
    const val coreKtx = "1.7.0"
    const val lifecycleRuntimeKtx = "2.3.1"
    const val activityCompose = "1.3.1"
    const val composeUi = "1.1.1"
    const val composeMaterial = "1.1.1"
    const val junit = "4.13.2"
    const val testExtJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val appcompat = "1.6.1"
    const val androidMaterial = "1.10.0"
    const val daggerHiltAndroid = "2.44"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val navigationCompose = "2.5.3"
    const val retrofit = "2.9.0"
    const val okhttp = "4.9.2"
    const val moshiKotlin = "1.13.0"
    const val converterMoshi = "2.9.0"
    const val loggingInterceptor = "4.9.2"
    const val kotlinxCoroutinesAndroid = "1.6.0"
    const val splashscreen = "1.0.0-alpha01"
    const val foundation = "1.4.0-alpha03"
    const val coilCompose = "2.2.0"
}